#ifndef APP_FEATURE_FLAGS_H
#define APP_FEATURE_FLAGS_H

#if defined(CONFIG_APP_LOW_POWER_FSM)
#define APP_LOW_POWER_FSM_ENABLED 1
#else
#define APP_LOW_POWER_FSM_ENABLED 0
#endif

#if defined(CONFIG_APP_DEEP_SLEEP_ENABLE)
#define APP_DEEP_SLEEP_ENABLED 1
#else
#define APP_DEEP_SLEEP_ENABLED 0
#endif

#if defined(CONFIG_APP_RETENTION_ENABLE)
#define APP_RETENTION_ENABLED 1
#else
#define APP_RETENTION_ENABLED 0
#endif

#if defined(CONFIG_APP_DEEP_SLEEP_SIMULATE)
#define APP_DEEP_SLEEP_SIMULATE_ENABLED 1
#else
#define APP_DEEP_SLEEP_SIMULATE_ENABLED 0
#endif

#if defined(CONFIG_APP_WAKEUP_SRC_BUTTON)
#define APP_WAKEUP_SRC_BUTTON_ENABLED 1
#else
#define APP_WAKEUP_SRC_BUTTON_ENABLED 0
#endif

#if defined(CONFIG_APP_WAKEUP_SRC_PERIODIC)
#define APP_WAKEUP_SRC_PERIODIC_ENABLED 1
#else
#define APP_WAKEUP_SRC_PERIODIC_ENABLED 0
#endif

#if defined(CONFIG_APP_WAKEUP_SRC_COMM)
#define APP_WAKEUP_SRC_COMM_ENABLED 1
#else
#define APP_WAKEUP_SRC_COMM_ENABLED 0
#endif

#if defined(CONFIG_APP_WAKEUP_SRC_RTC_ALARM)
#define APP_WAKEUP_SRC_RTC_ALARM_ENABLED 1
#else
#define APP_WAKEUP_SRC_RTC_ALARM_ENABLED 0
#endif

#if defined(CONFIG_APP_WAKEUP_SRC_SOUND)
#define APP_WAKEUP_SRC_SOUND_ENABLED 1
#else
#define APP_WAKEUP_SRC_SOUND_ENABLED 0
#endif

#if defined(CONFIG_APP_WAKEUP_SRC_LOW_BAT)
#define APP_WAKEUP_SRC_LOW_BAT_ENABLED 1
#else
#define APP_WAKEUP_SRC_LOW_BAT_ENABLED 0
#endif

#ifndef APP_GPS_LOCAL_TIME_OFFSET_HOURS
#define APP_GPS_LOCAL_TIME_OFFSET_HOURS 2
#endif

#endif /* APP_FEATURE_FLAGS_H */
