CONFIG_RETAINED_MEM_ZEPHYR_RAM=y
CONFIG_STM32_BACKUP_SRAM_INIT_PRIORITY=80

# Route the U5 application console/log UART backend through USB CDC ACM.
CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_DEVICE_STACK_NEXT=n
CONFIG_USB_COMPOSITE_DEVICE=y
CONFIG_USB_CDC_ACM=y
CONFIG_USB_DEVICE_INITIALIZE_AT_BOOT=y
CONFIG_UART_LINE_CTRL=y
